server:
  error:
    include-message: always
  forward-headers-strategy: native
  port: 18281
  servlet:
    context-path: /codebreaker-community

spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com